[package]
name = "longshot"
version = "0.1.2"
authors = ["Matt Mastracci <matthew@mastracci.com>"]
edition = "2021"
description = "API and CLI for ECAM-based Delonghi machines"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/mmastrac/longshot"
readme = "README.md"

[dependencies]
btleplug = "0.10.1"
tokio = { version = "1.21.1", features = ["io-std", "io-util", "macros", "rt", "rt-multi-thread", "process"] }
tokio-stream = { version = "0.1.10", features = ["sync", "io-util"] }
pretty_env_logger = "0.4.0"
uuid = "1.2.1"
hex = "0.4.3"
thiserror = "1.0.37"
clap = { version = "4.0.18", features = ["cargo"] }
async-stream = "0.3.3"
stream-cancel = "0.8.1"
tuples = "1.6.0"
futures = "0.3.25"
num_enum = "0.5.7"
enum-iterator = "1.2.0"
colored = "2"
lazy_static = "1.4.0"

[dev_dependencies]
rstest = "0.15.0"

[lib]
name = "longshot"

[[bin]]
name = "longshot"
path = "src/main.rs"
